// <auto-generated />
using System;
using AspVisitorManagement2018.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AspVisitorManagement2018.Migrations
{
    [DbContext(typeof(VisitorDbContext))]
    [Migration("20180723021736_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("AspVisitorManagement2018.Models.StaffNames", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Department");

                    b.Property<string>("Name");

                    b.Property<int>("VisitorCount");

                    b.HasKey("Id");

                    b.ToTable("StaffNames");
                });

            modelBuilder.Entity("AspVisitorManagement2018.Models.Visitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Business");

                    b.Property<DateTime>("DateIn");

                    b.Property<DateTime>("DateOut");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<int?>("StaffNameId");

                    b.HasKey("Id");

                    b.HasIndex("StaffNameId");

                    b.ToTable("Visitor");
                });

            modelBuilder.Entity("AspVisitorManagement2018.Models.Visitor", b =>
                {
                    b.HasOne("AspVisitorManagement2018.Models.StaffNames", "StaffName")
                        .WithMany()
                        .HasForeignKey("StaffNameId");
                });
#pragma warning restore 612, 618
        }
    }
}
